name: Template
main: gloyrock.template.main.Template
version: 0.0.1-SNAPSHOT
api-version: 1.13
author: Gloryrock
description: This is a plugin template.
permissions:
      template.commands.first:
        description: Allows first command
        default: true
      template.*:
        description: Wildcard permission
        default: false
        children:
          yeet.commands.yeet: true
commands:
   first:
      description: First command
      permission: template.commands.first
      permission-message: You do not have permission!
      usage: /first